# Release configuration for Python projects
release:
  # Git Flow 標準分支模式 - 僅使用單一 release 分支
  # 遵循標準 Git Flow 實踐，便於團隊協作和分支管理
  branch_patterns:
    - "release"     # 標準 Git Flow release 分支
    - "main"        # 生產環境主分支
    - "master"      # 舊版主分支 (向後相容)
  
  # 移除的模式說明:
  # - "release/*"   # 不建議：會產生多個 release 分支
  # - "releases/*"  # 不建議：非標準命名方式
    
  # Version validation settings
  version_check:
    enabled: true
    changelog_file: "CHANGELOG.md"
    version_files:
      - "setup.py"
      - "pyproject.toml"
      - "src/*/__init__.py"
      - "*/__init__.py"
    
    # Supported changelog formats
    changelog_formats:
      - "keepachangelog"  # [1.0.0] - 2024-01-01
      - "simple"          # v1.0.0
    
    # Version validation rules
    version_pattern: "^(\\d+\\.\\d+\\.\\d+)$"  # semver
    allow_prerelease: true
    prerelease_pattern: "^(\\d+\\.\\d+\\.\\d+)-(alpha|beta|rc)\\d*$"
    
  # Build settings
  build:
    enabled: true
    output_dir: "dist"
    clean_before_build: true
    build_systems:
      - "setuptools"      # python setup.py bdist_wheel
      - "build"           # python -m build
      - "poetry"          # poetry build
    
    # Build validation
    validate_wheel: true
    check_metadata: true
    
  # Testing settings
  testing:
    enabled: true
    venv_dir: ".release-test-env"
    python_executable: "python"
    test_command: "pytest"
    test_args: "--tb=short -v"
    
    # Requirements files to install
    requirements_files:
      - "requirements.txt"
      - "requirements-dev.txt"
    
    # Test markers to run/skip
    test_markers:
      include: []
      exclude: ["slow", "integration"]
    
    # Coverage settings
    coverage:
      enabled: false
      min_coverage: 80
    
  # GitHub integration
  github:
    enabled: true
    create_tag: true
    create_release: true
    
    # Release assets to upload
    upload_assets:
      - "dist/*.whl"
      - "dist/*.tar.gz"
      - "CHANGELOG.md"
      - "README.md"
      - "LICENSE"
    
    # Release notes generation
    release_notes:
      auto_generate: true
      include_changelog: true
      changelog_section: "latest"  # or "all"
    
    # Repository settings
    repository:
      owner: ""  # Will be auto-detected
      name: ""   # Will be auto-detected
      
  # Notification settings
  notifications:
    enabled: false
    slack:
      webhook_url: ""
      channel: "#releases"
    email:
      recipients: []
      
  # Security settings
  security:
    scan_secrets: true
    allowed_files_size: "10MB"
    
  # Rollback settings
  rollback:
    enabled: true
    backup_branch: "backup/release-{version}"
    
# Environment-specific overrides
environments:
  development:
    testing:
      test_markers:
        exclude: ["slow"]
    github:
      create_release: false
      
  staging:
    github:
      create_release: false
      
  production:
    testing:
      test_markers:
        exclude: []
    github:
      create_release: true